"""Render a reproducible model turntable for the README (not a screen recording).

.venv-blender/bin/python scripts/render_turntable.py
.venv/bin/python scripts/make_gif.py
"""
from pathlib import Path
import argparse
import math
import bpy
from mathutils import Vector

ROOT=Path(__file__).resolve().parents[1]/"models/x5"
parser=argparse.ArgumentParser()
parser.add_argument("--frames",type=int,default=60)
args=parser.parse_args()
if args.frames<4:parser.error("At least four frames are required")
folder=ROOT/"preview/turntable_frames"
folder.mkdir(exist_ok=True)
# Remove only frames previously generated by this script.
for old in folder.glob("frame_*.png"):old.unlink()
bpy.ops.wm.open_mainfile(filepath=str(ROOT/"assets/x5_source.blend"))
scene=bpy.context.scene
scene.render.engine="CYCLES"
scene.cycles.samples=24
scene.cycles.use_denoising=True
scene.render.resolution_x=640
scene.render.resolution_y=800
scene.render.resolution_percentage=100
scene.render.image_settings.file_format="PNG"
scene.render.film_transparent=True
scene.view_settings.view_transform="AgX"
scene.world.use_nodes=True
background=scene.world.node_tree.nodes["Background"]
background.inputs[0].default_value=(.55,.60,.70,1)
background.inputs[1].default_value=.3
def light(name,pos,power,size,color):
    data=bpy.data.lights.new(name,"AREA")
    data.energy=power; data.shape="DISK"; data.size=size;data.color=color
    obj=bpy.data.objects.new(name,data)
    bpy.context.collection.objects.link(obj); obj.location=pos
    obj.rotation_euler=(Vector((0,0,.063))-obj.location).to_track_quat("-Z","Y").to_euler()
light("key",(.2,.15,.22),.8,.2,(.91,.95,1))
light("rim",(-.12,-.09,.19),1.2,.12,(.65,.78,1))
light("fill",(.06,-.2,.04),.5,.15,(1,.92,.83))
camdata=bpy.data.cameras.new("turntable_camera")
cam=bpy.data.objects.new("turntable_camera",camdata)
bpy.context.collection.objects.link(cam)
scene.camera=cam;camdata.type="ORTHO";camdata.ortho_scale=.158;camdata.clip_start=.001
for index in range(args.frames):
    angle=math.radians(32)+math.tau*index/args.frames
    cam.location=(.27*math.cos(angle),.27*math.sin(angle),.136)
    cam.rotation_euler=(Vector((0,0,.061))-cam.location).to_track_quat("-Z","Y").to_euler()
    scene.render.filepath=str(folder/f"frame_{index:04d}.png")
    bpy.ops.render.render(write_still=True)
    print(f"TURNTABLE {index+1}/{args.frames}",flush=True)
